---
- hosts: main-routers,branch-routers
  gather_facts: false
  vars_prompt:
    - name: username
      private: false
      prompt: "Input your username"
    - name: password
      prompt: "Input your password: "
  vars:
    ansible_connection: network_cli
    ansible_network_os: vyos
    ansible_user: "{{ username }}"
    ansible_password: "{{ password }}"
    authorize: true
    transport: cli

  tasks:
    - name: Ping the hosts
      ping:
    - name: Configure virtual interface address
      vyos.vyos.vyos_vlan:
        vlan_id: 100
        interfaces: eth1
        address: 172.26.100.37/24






