---
- name: Gather Routers Facts
  hosts: routers
  gather_facts: false

  tasks:
    - name: Perform interface check if device is reachable
      vyos.vyos.vyos_command:
        commands:
          - show interfaces
        wait_for:
          - result[0] contains 'Interface'
      register: vyos_interfaces
      when: ansible_facts['reachable'] == true

    - name: Display if not reachable
      debug:
        msg: "Device {{ inventory_hostname }} is not reachable!"
      when: ansible_facts['reachable'] != true

        
    # - name: Configure virtual interface address
    #   vyos.vyos.vyos_vlan:
    #     vlan_id: 100
    #     interfaces: eth1
    #     address: 172.26.100.37/24






