---
- hosts: routers
  gather_facts: false
  tasks:
    - name: Check routers availability
      ping:
    - name: Gather Interfaces facts
      vyos.vyos.vyos_facts:
        gather_network_resources:
        - interfaces
      register: vyos_interfaces
    - name: Display facts
      debug:
        var: vyos_interfaces
        
    # - name: Configure virtual interface address
    #   vyos.vyos.vyos_vlan:
    #     vlan_id: 100
    #     interfaces: eth1
    #     address: 172.26.100.37/24






