---
- hosts: routers
  gather_facts: false

  tasks:
    - name: Ping the hosts
      ping:
    - name: Configure virtual interface address
      vyos.vyos.vyos_vlan:
        vlan_id: 100
        interfaces: eth1
        address: 172.26.100.37/24






