---
- hosts: main-routers,branch-routers
  gather_facts: false
  tasks:
    - name: Ping the hosts
      ping:
    - name: Gather Facts
      vyos.vyos.vyos_facts:
        gather_subset: config





