---
- name: Gather Routers Facts
  hosts: routers
  gather_facts: false
  tasks:

    - name: Perform interface check
      vyos.vyos.vyos_command:
        commands:
        - show interface
        wait_for:
        - result[0] contains 'Interface'
      register: vyos_interfaces
      debug:
        msg: "{{ vyos_interfaces.stdout_lines }}"
      when: ansible_facts['reachable'] == true

    - name: Display in not reachable
      debug:
        msg: "Device {{ inventory_hostname }} is not reachable!"
        
    # - name: Configure virtual interface address
    #   vyos.vyos.vyos_vlan:
    #     vlan_id: 100
    #     interfaces: eth1
    #     address: 172.26.100.37/24






