---
- name: Gather Routers Facts
  hosts: routers
  gather_facts: false

  tasks:
    - name: Check device availability
      ping: 
      register: ping_result

    - name: Perform interface check on devices
      vyos.vyos.vyos_command:
        commands:
          - show interfaces
        wait_for:
          - result[0] contains 'Interface'
      register: vyos_interfaces

      set_fact:
        interfaces:
          - name: "{{ item.split()[0] }}"
            ip_address: "{{ item.split()[1] }}"
            status: "{{ item.split()[2] }}"
            description: "{{ item.split()[3] | default('') }}"
      with_items: "{{ interface_info.msg[0] }}"
      when: item does not contain 'Interface' or 'IP Address' or 'S/L' or 'Description' or '---'
    
    - name: Display the interfaces of the device
      debug:
        msg: "{{ vyos_interfaces.stdout_lines }}"

        
    # - name: Configure virtual interface address
    #   vyos.vyos.vyos_vlan:
    #     vlan_id: 100
    #     interfaces: eth1
    #     address: 172.26.100.37/24






