---
- name: Gather Routers Facts
  hosts: routers
  gather_facts: false

  tasks:
    - name: Perform interface check on Routers
      vyos.vyos.vyos_command:
        commands:
          - show interfaces
        wait_for:
          - result[0] contains 'Interface'
      register: vyos_interfaces

    - name: Display the inerfaces of the device
      debug:
        msg: "{{ int_detail }}"

    # - name: Parse and save data to variables
    #   set_fact:
    #     interfaces_arr: []
    #   loop: "{{ msg.splitlines() }}"
    #   loop_control:
    #     loop_var: line
    #   when: line | regex_search('^\\w+\\s+\\d+\\.')
    #   vars:
    #     parsed_line: "{{ line.split() }}"
    #   set_fact2:
    #     interfaces_arr: "{{ interfaces + [{
    #       'name': parsed_line[0],
    #       'ip_address': parsed_line[1],
    #       'status': parsed_line[2],
    #       'description': parsed_line[3] | default('')}] }}"

    # - name: Display the interfaces of the device
    #   debug:
    #     var: interfaces

        
    # - name: Configure virtual interface address
    #   vyos.vyos.vyos_vlan:
    #     vlan_id: 100
    #     interfaces: eth1
    #     address: 172.26.100.37/24






