---
- name: Print IP addresses of specific hosts
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Set IP addresses of all hosts
      set_fact:
        host_ips:
          stg_roulette_ip: "{{ hostvars['STG-ROULETTE'].host_ip_address }}"
          stg_sicbo_ip: "{{ hostvars['SICBO-STG'].host_ip_address }}"
          stg_blackjack_ip: "{{ hostvars['BLACKJACK-STG'].host_ip_address }}"
          prod_bccA_ip: "{{ hostvars['BACCARAT-A'].host_ip_address }}"
          prod_bccB_ip: "{{ hostvars['BACCARAT-B'].host_ip_address }}"
          prod_bccC_ip: "{{ hostvars['BACCARAT-C'].host_ip_address }}"
          prod_bccD_ip: "{{ hostvars['BACCARAT-D'].host_ip_address }}"
          prod_bccE_ip: "{{ hostvars['BACCARAT-E'].host_ip_address }}"
          prod_bccF_ip: "{{ hostvars['BACCARAT-F'].host_ip_address }}"
          prod_bccG_ip: "{{ hostvars['BACCARAT-G'].host_ip_address }}"
          prod_bccH_ip: "{{ hostvars['BACCARAT-H'].host_ip_address }}"
          prod_bccI_ip: "{{ hostvars['BACCARAT-I'].host_ip_address }}"
          prod_dtA_ip: "{{ hostvars['DRAGON-TIGER-A'].host_ip_address }}"
          prod_dtB_ip: "{{ hostvars['DRAGON-TIGER-B'].host_ip_address }}"
          prod_rltA_ip: "{{ hostvars['ROULETTE-A'].host_ip_address }}"
          prod_rltB_ip: "{{ hostvars['ROULETTE-B'].host_ip_address }}"
          prod_rltC_ip: "{{ hostvars['ROULETTE-C'].host_ip_address }}"
          prod_sicA_ip: "{{ hostvars['SICBO-A'].host_ip_address }}"
          prod_sicB_ip: "{{ hostvars['SICBO-B'].host_ip_address }}"
          prod_bjA_ip: "{{ hostvars['BLACKJACK-A'].host_ip_address }}"

    - name: Print IP addresses of all specified hosts
      debug:
        msg: "{{ item.key }} IP address is {{ item.value }}"
      with_dict: "{{ host_ips }}"
